### ISSUE TITLE
Intervaltree objects cannot be pickled

### ISSUE THREAD

**Issue by endrebak** [brentp/quicksect#6]
This creates an error for me when I try to multithread. Are you familiar with this problem? Any ideas whether it will be hard to fix?

**Comment by endrebak** [comment]
Thanks for the package btw.

**Comment by brentp** [comment]
`__reduce__` and `__setstate__` are written, so it should work, but I haven't used that code for some time so it must have some bitrot. I suspect it would be a quick fix, but I don't have the bandwidth to look into it this week.

**Comment by endrebak** [comment]
Thanks! Only do it if and whenever it is convenient. I should try to make a reproducible example. 

Also, I factored out clustertrees because bx-python had some hard-to-install compression dependencies in addition to the python version problem. Dunno if it is of interest: https://github.com/endrebak/clustertrees

**Comment by brentp** [comment]
as it turns out, there are tests for pickling. so might be something with your use-case.

**Comment by endrebak** [comment]
Or that joblib parallel does something weird. I'll reproduce so that I can start to look into it.

**Comment by endrebak** [comment]
```

from quicksect import IntervalTree

from joblib import Parallel, delayed


def _fill_tree(t):

    for i, pos in enumerate([0, 50, 100]):
        t.add(pos, pos+1, i)

    return t


def _create_tree(_):

    t = IntervalTree()
    for i, pos in enumerate([0, 50, 100]):
        t.add(pos, pos+1, i)

    return t


def try_create():

    trees = Parallel(n_jobs=2)(delayed(_create_tree)(c) for c in "chr1 chr2".split())


def try_fill():

    trees = Parallel(n_jobs=2)(delayed(_fill_tree)(IntervalTree()) for c in "chr1 chr2".split())


try_create()
```

both give approx the same error message:

```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    try_create()
  File "test.py", line 26, in try_create
    trees = Parallel(n_jobs=2)(delayed(_create_tree)(c) for c in "chr1 chr2".split())
  File "/home/endrebak/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/home/endrebak/anaconda3/lib/python3.6/site-packages/joblib/parallel.py", line 699, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/endrebak/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<quicksect.IntervalTree object at 0x7f35f9f302b0>]'. Reason: 'TypeError("can't pickle quicksect.IntervalTree objects",)'
```

I'll try to see if it works with Python's native multiprocessing to ensure this isn't joblib (https://pythonhosted.org/joblib/generated/joblib.Parallel.html)

**Comment by endrebak** [comment]
A hackaround might be to use `_create_tree` and pickle it manually in each process. This is ugly though XD

**Comment by endrebak** [comment]
I have looked into it and Intervaltrees are not pickleable, but intervals are. That is the problem.

```
In [31]: i = Interval(0, 10)

In [32]: pickle.dumps(i)
Out[32]: b'\x80\x03cquicksect\nInterval\nq\x00K\x00K\n\x86q\x01Rq\x02}q\x03X\x04\x00\x00\x00dataq\x04Nsb.'

In [33]: t = IntervalTree()

In [34]: t.add(0, 10, 5)

In [35]: pickle.dumps(t)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-f90063f6658b> in <module>()
----> 1 pickle.dumps(t)

TypeError: can't pickle quicksect.IntervalTree objects
```

Dunno how to fix this, but I'd love to help as this creates a major bottleneck in one of my software packages :)

**Comment by endrebak** [comment]
```python
def hoo(_):
    t = IntervalTree()
    for i, pos in enumerate([0, 50, 100]):
        t.add(pos, pos+1, i)

    start, end, nums = t.search(0,1000)

    return start, end, nums

p = multiprocessing.Pool(2); p.map(hoo, cs)
```

This is not optimal from a design-perspective, but when you need speed the code isn't always pretty :)

Perhaps the easiest thing to do is not to fix this, but just write a caveat in the docs?

**Comment by brentp** [comment]
hmm. well you can implement `__reduce__` for the Tree. It will have to output dicts. and then `__setstate__` can re-build the tree.

**Comment by endrebak** [comment]
I desperately need multithreaded use of intervaltrees for https://github.com/endrebak/pyranges which is slow as molasses compared to bioconductor for building GRanges objects (but not the operations themselves). So I'll start to look into this.

**Comment by endrebak** [comment]
Some testing showed that quicksect would not be fast enough to compete with bioconductor GRanges so I made this instead: https://github.com/endrebak/kerneltree

**Comment by brentp** [comment]
I'm suprised that quicksect is much slower than GRanges. Glad you found a solution, I didn't know about the interval tree in the linux kernel.

**Comment by endrebak** [comment]
Dunno if you are interested, but I just found and wrapped this datastructure called a nested containment list which seems to be > 100x faster than the fastest intervaltrees. Crazy stuff.

https://github.com/endrebak/ncls

**Comment by brentp** [comment]
not at all. it's interesting to follow. maybe since starts and ends were already sorted in your test-case it works out?

**Comment by endrebak** [comment]
This is actually from pygr, but it seems to work really quickly. The constructor calls [build_nested_list](https://github.com/hunt-genes/ncls/blob/master/src/ncls.pyx#L92) which uses very little time. I have only tested the C-API for time, perhaps the old python wrapper was suboptimal. Also, I have not done much testing on the queries.

The large tests were done like this, on unsorted data:

```
total_nb = int(1e8)

starts = randint(0, int(1e8), total_nb)
ends = starts + 100
values = np.array(range(total_nb))
```

ncls is also the datastructure genomicranges started using because they found it to be faster. 

The Julia people were not impressed though: https://github.com/BioJulia/Bio.jl/issues/340

**Comment by endrebak** [comment]
(Will create better timings, but it seems that even on completely randomly shuffled data, the NCLS were 4 times faster to build than the kerneltrees, which is a significant speedup.)

**Comment by brentp** [comment]
nice. yes, even 4X is a big improvement.
